spring:
    application:
        name: user
    datasource:
        url: jdbc:mysql://localhost:3306/user
        username: user
        password: user
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8081