version: '3.6'

services:
    db:
        image: mysql:8.4.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: user
        ports:
            - "3306:3306"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
    rabbitmq:
        image: rabbitmq:3.13.6-management
        ports:
            - "5672:5672"
            - "15672:15672"