services:
    db_user:
        image: mysql:8.4.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: user
        ports:
            - "3306:3306"
    db_shop:
        image: mysql:8.4.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: shop
        ports:
            - "3307:3307"
        command:
            - --port=3307
    db_order:
        image: mysql:8.4.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: order
        ports:
            - "3308:3308"
        command:
            - --port=3308
    rabbitmq:
        image: rabbitmq:3.13.6-management
        ports:
            - "5672:5672"
            - "15672:15672"