version: '3.6'

services:
    db:
        image: mysql:8.0.32
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: user
        ports:
            -   "3306:3306"
        volumes:
            -   ./init:/docker-entrypoint-initdb.d