spring:
    application:
        name: shop
    datasource:
        url: jdbc:mysql://localhost:3306/shop
        username: user
        password: user
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
server:
    port: 8082
user-service:
    url: http://localhost:8081
rabbitmq:
    name:
        queue: order_details_queue
        exchange: generate_bill
    routing:
        key: bill_key
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /docs