spring:
    application:
        name: order
    datasource:
        url: jdbc:mysql://localhost:3306/order
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8083
user-service:
    url: http://localhost:8081
rabbitmq:
    name:
        queue: order_details_queue
        exchange: generate_bill
    routing:
        key: bill_key
